### ISSUE TITLE
[Feature Request] Add a flag to not add commented out code to the output file.

### ISSUE THREAD

**Issue by benjaminlgur** [chand1012/git2gpt#5]
Can be useful to reduce context for context size sensitive applications.

**Comment by chand1012** [comment]
Ignoring commented out code specifically could be tricky, however I think just ignoring comments should be a good temporary compromise until I can find the time to properly implement ignoring code. I'll update when I'm finished.

**Comment by chand1012** [comment]
See #6 for a WIP PR.
