### ISSUE TITLE
Can it instantly make a zip?

### ISSUE THREAD

**Issue by nikivdev** [chand1012/git2gpt#7]
ChatGPT only accepts zip if content is too large.

I just ran git2gpt on this repo https://github.com/graphql/graphql-spec

and got 

<img width="758" alt="image" src="https://github.com/chand1012/git2gpt/assets/6391776/35e45520-234d-458e-9976-d4472086126d">

I can't attach this as context

<img width="377" alt="image" src="https://github.com/chand1012/git2gpt/assets/6391776/80aba370-c031-4636-a6fc-63d64f993d61">

I need `.zip` put into my clipboard that I can paste. 

Or I am confused how to work with this.

Thanks.

**Comment by nikivdev** [comment]
yea I just got

<img width="850" alt="image" src="https://github.com/chand1012/git2gpt/assets/6391776/eb6b54f8-f7b6-4b14-a167-e06a021a5152">

**Comment by nikivdev** [comment]
<img width="575" alt="image" src="https://github.com/chand1012/git2gpt/assets/6391776/522f7fe5-232f-46fa-87de-3d484357308c">

trying this

**Comment by nikivdev** [comment]
<img width="912" alt="image" src="https://github.com/chand1012/git2gpt/assets/6391776/412fe146-4c8b-45ef-8aa1-9806f5a520cc">

yea its failing

I don't know how I can instantly turn a git repo into something I can then instantly paste into chatgpt for context 

thank you for any help 🖤

**Comment by nikivdev** [comment]
<img width="805" alt="image" src="https://github.com/chand1012/git2gpt/assets/6391776/ddfc8470-9d65-44ac-86b7-0881ce41e464">

tried to manually add zip too, it ignores the zip completely as context

yea super confused

**Comment by nikivdev** [comment]
<img width="837" alt="image" src="https://github.com/chand1012/git2gpt/assets/6391776/9b8c30a2-3c90-4cd8-bd37-4f45c1b7f094">

seems like I have to tell gpt to use the uploaded content, it doesn't do it automatically

still point stands I'd like to have command similar to `git2gpt .` that will put into clipboard a `.zip` I can paste into GPT as context (I don't want to go through manually choosing the .zip in file picker (if I can avoid it)

**Comment by chand1012** [comment]
Here's a bash script that should accomplish what you're looking for.

```bash
# Only works on Mac!!!!!
# https://apple.stackexchange.com/a/15542
file-to-clipboard() {
    osascript \
        -e 'on run args' \
        -e 'set the clipboard to POSIX file (first item of args)' \
        -e end \
        "$@"
}

git ls-files | zip ~/repo.zip -@ && file-to-clipboard ~/repo.zip
```

This will let you paste as a file in applications like ChatGPT or Telegram.

**Comment by nikivdev** [comment]
turned it into fish shell

```
function fileToClipboard
    osascript \
        -e 'on run args' \
        -e 'set the clipboard to POSIX file (first item of args)' \
        -e end \
        $argv
end

function turnCurrentFolderIntoZipForGpt
    git ls-files | zip ~/do/repo.zip -@; and fileToClipboard ~/do/repo.zip
    # rm -rf ~/do/repo.zip
end
```

But for some reason either fish shell or bash solution you have fails to upload to ChatGPT.

**Comment by nikivdev** [comment]
Made a video recording of it here with more context: https://www.loom.com/share/972fe7714a894376b5624c770017666f

Thank you for help 🖤

**Comment by nikivdev** [comment]
This happens in bash too with:

```
file-to-clipboard() {
    osascript \
        -e 'on run args' \
        -e 'set the clipboard to POSIX file (first item of args)' \
        -e end \
        "$@"
}

git ls-files | zip ~/repo.zip -@ && file-to-clipboard ~/repo.zip
```

tested on this repo https://github.com/openai/openai-assistants-quickstart

and on GPT-4

**Comment by chand1012** [comment]
Does it work when you download the zip from GitHub?

**Comment by nikivdev** [comment]
<img width="1129" alt="image" src="https://github.com/chand1012/git2gpt/assets/6391776/7c7e539b-d27d-41a0-862e-eae6ee31f371">

Yea I guess its issue of zip itself indeed.

**Comment by nikivdev** [comment]
going to trying some other repos with zip, not really sure why it fails, its not even a large repo 🤔

**Comment by chand1012** [comment]
Going to close since this issue seems unrelated to core functionality.
